# Generated by Django 5.2.8 on 2025-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problema',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='problema',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='problemas_imagens/'),
        ),
    ]
